apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: acceptence-test
spec:
  inputs:
    resources:
    - name: wiki-application
      type: git

  steps:
  - name: acceptence-test
    image: golang
    workingDir: /workspace/wiki-application
    script: |
      #!/usr/bin/env sh
      make acceptance
    securityContext:
      privileged: true