apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: ci-wiki-application
spec:
  resources:
    - name: wiki-application
      type: git

    - name: built-image
      resourceRef:
        name: wiki-image

  tasks:
    - name: lint-test
      taskRef:
        name: lint-test
      resources:
        inputs:
        - name: wiki-application
          resource: wiki-application

    - name: unit-test
      taskRef:
        name: unit-test
      resources:
        inputs:
        - name: wiki-application
          resource: wiki-application

    - name: e2e-test
      taskRef:
        name: e2e-test
      runAfter:
        - lint-test
        - unit-test
      resources:
        inputs:
        - name: wiki-application
          resource: wiki-application

    - name: acceptence-test
      taskRef:
        name: acceptence-test
      runAfter:
        - lint-test
        - unit-test
      resources:
        inputs:
        - name: wiki-application
          resource: wiki-application


    - name: build-task
      runAfter: ['e2e-task', 'acceptance-task']
      taskRef:
        name: build-image
      resources:
        inputs:
        - name: wiki-application
          resource: wiki-application
        outputs:
        - name: dest-image
          resource: built-image

    - name: deploy-task
      runAfter: [build-task]
      taskRef:
        name: deploy-application
      resources:
        inputs:
        - name: new-image
          resource: built-image
